version: "3.3"
services: 
    postgresdb:
        image: postgres:latest
        env_file: 
            - .env
        ports: 
            - '5432:5432'
        volumes: 
            - data:/var/lib/postgres
        networks: 
            - mynetwork
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 30s
            timeout: 30s
            retries: 3

    server:
        build: 
            context: .
            dockerfile: Dockerfile
        env_file: .env
        depends_on:
            - postgresdb
        networks: 
            - mynetwork
        ports: 
            - '8888:8888'
        restart: on-failure
        links: 
            - postgresdb

networks: 
    mynetwork:
        driver: bridge

volumes: 
    data: